### PR TITLE
update(): update to NodeJS 10 or OpenSSL 1.1.0 (closes #167)

### LINKED ISSUE #167: nodejs 10.0.0 build failed
macos 10.13.4
node 10.0.0
```

> ursa@0.9.4 install /Users/gaojinceon/WebstormProjects/dianziyan/node_modules/ursa
> node-gyp rebuild

  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
../src/ursaNative.cc:389:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->n = BN_bin2bn(data_n, n_length, NULL);
            ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:390:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->e = BN_bin2bn(data_e, e_length, NULL);
            ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:407:35: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    if ((obj == NULL) || (obj->rsa->d != NULL)) {
                                  ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:536:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->e);
                                 ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:552:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->d);
                                 ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:567:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->n);
                                 ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1218:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1219:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1220:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->p = p;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1221:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->q = q;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1222:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmp1 = dp;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1223:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmq1 = dq;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1224:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->iqmp = inverseQ;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1225:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->d = d;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1270:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1271:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/gaojinceon/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
16 errors generated.
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1

```

### PR DESCRIPTION
**Pull request by jkuri**
I made it backward compatible with previous NodeJS/OpenSSL versions.

### CODE REVIEW

**Comment by lognaturel** [comment]
Confirmed working well on macOS 10.13.4, node v10.2.1. Thanks, @jkuri!

**Comment by deluxor** [comment]
Working perfectly on Linux, with latest Node 10.1.0 and NPM 6.1.0
Good job!

```
> ursa@0.9.4 install /home/deluxor/home/Loqr/lcp-node-sdk/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/home/deluxor/home/Loqr/lcp-node-sdk/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
  SOLINK_MODULE(target) Release/obj.target/ursaNative.node
  COPY Release/ursaNative.node
make: Leaving directory '/home/deluxor/home/Loqr/lcp-node-sdk/node_modules/ursa/build'
updated 3 packages and audited 111 packages in 9.455s
```

**Comment by LoganDark** [comment]
It works, so merge it please, production code is failing because I can't build this on a Compute Engine instance.

**Comment by LoganDark** [comment]
Thank you!

**Comment by jkuri** [comment]
@JoshKaufman thanks for merging, can you also publish a new version to `npm` please?

**Comment by mtgto** [comment]
I'm also waiting for publishing 😂😂😂

**Comment by bmunkholm** [comment]
Please @JoshKaufman can publish? Or alternatively, give others rights to do so? It's highly preferred from forking and maintaining that.

**Comment by delfuego** [comment]
Will this ever make it to npm? It's much harder to do CI builds without there being a dependable npm source for this fix.

**Comment by JonasRech** [comment]
@quartzjer as the new maintainer, could you please do a publish to NPM? It can't be so hard...
